### ISSUE TITLE
[Library manager] Please add Anyleaf

### ISSUE THREAD

**Issue by David-OConnor** [arduino/Arduino#10250]
Github repo: https://github.com/AnyLeaf/ph-cpp

Please let me know if there's anything you'd like me to change, or if you need more info.

**Comment by cmaglie** [comment]
Done.

**Comment by njh** [comment]
It looks like the AnyLeaf `ph-cpp` repo for Arduino has now been deleted.

Is there any information about why?

**Comment by David-OConnor** [comment]
I restructured the way its repo interacts with it's sister repos, and had a
typo in the name. Fixed.

**Comment by njh** [comment]
Ah, ok.

I am still getting a 404 for:
https://github.com/AnyLeaf/ph-cpp

**Comment by David-OConnor** [comment]
Oops, was set in Private mode! Fixed.

(If you'd like more details, I have drivers for this hardware in 3 languages, all which share a same repo to make it easier to manage. I then push the language-specific subfolders to individual repos, one of which is this.)
