### ISSUE TITLE
Mac OS X 10.10 Problem

### ISSUE THREAD

**Issue by dyvitis** [arduino/Arduino#2384]
I recently upgraded to OS X Yosemite and Java 1.8. Upon attempting to start Arduino app, I get an error as follows:
Arduino quit unexpectedly.

Please advise.
Many thanks

**Comment by tcurdt** [comment]
Installing a legacy runtime cannot be the answer. The IDE should run with java 8, too.

**Comment by michaeltandy** [comment]
I've been able to get it working with the 1.5.8 Beta release named "Mac OS X: ZIP file for Java 7" from [the download page](http://arduino.cc/en/main/software#toc3) - it doesn't run if you double-click Arduino.app but I've been able to launch the IDE, compile and program Uno boards.

After copying Arduino.app into my Applications folder, I just did this in the terminal:
```
cd /Applications/Arduino.app/Contents/Java
java -cp antlr.jar:apple.jar:commons-codec-1.7.jar:commons-exec-1.1.jar:commons-httpclient-3.1.jar:commons-logging-1.0.4.jar:core.jar:ecj.jar:jmdns-3.4.1.jar:jna.jar:jsch-0.1.50.jar:jssc-2.8.0.jar:pde.jar processing.app.Base
```

Here are my java version details:
```
$ java -version
java version "1.8.0-ea"
Java(TM) SE Runtime Environment (build 1.8.0-ea-b84)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b25, mixed mode)
```

I was under the impression Java tries pretty hard to keep new JVM releases compatible with jars targeting older Java versions; I'd be interested to hear, if anyone knows, why the launcher isn't happy with Java 8 given that Processing seems fine with it.

**Comment by ffissore** [comment]
Can you try version "macosx-new" from https://github.com/arduino/Arduino/pull/2590#issuecomment-72337128 ?

**Comment by tcurdt** [comment]
macosx-new starts fine for me - but now I already have the legacy java installed already. Not sure how to figure out which runtime it uses.

**Comment by ffissore** [comment]
Don't know either. The "-new" version should not work with java <= 6. But a way to know which version is using would be nice to have. Maybe a plain `lsof | grep -i java` ?

**Comment by tcurdt** [comment]
Good idea. From `lsof` it looks like it picked the old runtime. Not so eager to de-install it just to try.

**Comment by ffissore** [comment]
I'm not sure lsof works as expected, though

**Comment by michaeltandy** [comment]
@ffissore I downloaded arduino-PR-2590-BUILD-142-macosx.zip (the file had an sha1 of c942411f294156e3737c8495b44863ed9db6857a ) from https://github.com/arduino/Arduino/pull/2590#issuecomment-72482121

Unfortunately, when I try to open it, I still get the message "To open “Arduino.app” you need to install the legacy Java SE 6 runtime."

Next, I installed arduino-PR-2590-BUILD-142-macosx-new.zip (the file had an sha1 of f810ccee173069c691be93c8c2198dfabe4344e8 ) from https://github.com/arduino/Arduino/pull/2590#issuecomment-72482685 - this time I received the message "“Arduino.app” can’t be opened because it is from an unidentified developer." - when I looked in the package, it didn't contain a "_CodeSignature" folder.

My computer's details:
```
Michaels-Mini:Downloads mtandy$ java -version
java version "1.8.0-ea"
Java(TM) SE Runtime Environment (build 1.8.0-ea-b84)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b25, mixed mode)

Michaels-Mini:Downloads mtandy$ uname -a
Darwin Michaels-Mini.lan 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
```

**Comment by tcurdt** [comment]
That still sounds like progress :)

In preferences "Security & Privacy > General > Allow apps downloaded from" (at least for the test) switch it to "Anywhere". If that works all is left is signing the release properly.

**Comment by michaeltandy** [comment]
As the -new file wasn't in the comment by @ArduinoBot I figured it wasn't from the build server - but looking at the ant file I see it was from the build server, just not in the comment.

![Unable to load Java Runtime Environment](http://i.imgur.com/SAHfgd4.png)

Pretty unhelpful error message, eh?

I tried these at the command line, hoping to get some debug info on stdout, but I didn't get anything:
```
$ open Arduino.app
$ Arduino.app/Contents/MacOS/Arduino
```

**Comment by ffissore** [comment]
It's not yet in the comment since PR builder has to work with all PRs. It will eventually be.

The error message is expected and it's the reason why we'll keep on pushing the *normal* version, which requires java6, the package of which is managed by Apple.
Please remember that the -new version is only for those who have troubles running the "normale" one.

Since Java7, Apple doesn't provide a Java package any more. You need to download a recent jre on your own (from http://java.com/it/download/). Then the IDE will run fine

**Comment by ffissore** [comment]
@michaeltandy only now I see you already have java. Can you paste the output of
`/usr/libexec/java_home -V` ?

**Comment by ffissore** [comment]
@tcurdt @michaeltandy Automated builds (everything but the released versions you find on the [download page](http://arduino.cc/en/Main/Software)) are **not** signed

**Comment by tcurdt** [comment]
> The error message is expected and it's the reason why we'll keep on pushing the normal version, which requires java6, the package of which is managed by Apple.

Since Mavericks it's a hassle to install the old version and the installation of a newer runtime is recommended. That's what should be communicated to the users giving them instructions on how to install the runtime.

I also had java8 installed when I came here.

> Since Java7, Apple doesn't provide a Java package any more. You need to download a recent jre on your own (from http://java.com/it/download/). Then the IDE will run fine

The problem is that with the "normal" version it will not run fine. People come here because they do have java but are forced to search, find and install a legacy package to install java6 to get the IDE running - despite the already installed newer runtime.

**Comment by ffissore** [comment]
Yes, helping users with issues is the whole point of this "-new" version.

When people run the IDE, and mac says there's a requirement, and everything is done with a no-brainer sequence of "yes, ok, continue", that's is far easier to explain.
People that say "no, I already have installed java, I won't install this old 6 thing" they **already** are advanced users and we'll provide a dedicated guide.

This will only happen once we've released

**Comment by tcurdt** [comment]
> everything is done with a no-brainer sequence of "yes, ok, continue", that's is far easier to explain

@ffissore that's how it was before - unfortunately that's no longer true on Mavericks

**Comment by ffissore** [comment]
And there will be a dedicated guide :) Trust me, at the end, it will look easy (hopefully it will **be** easy ;)). Now we are polishing the code. Documentation will follow

**Comment by michaeltandy** [comment]
@ffissore Command output:

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (3):
    1.8.0, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
    1.7.0_51, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_51.jdk/Contents/Home
    1.7.0_17, x86_64:	"Java SE 7"	/Library/Java/JavaVirtualMachines/jdk1.7.0_17.jdk/Contents/Home
```

I decided to dump 1.7 and followed [Oracle's instructions](http://docs.oracle.com/javase/7/docs/webnotes/install/mac/mac-jdk.html#uninstall) - after doing this the result was:

```
$ /usr/libexec/java_home -V
Matching Java Virtual Machines (1):
    1.8.0, x86_64:	"Java SE 8"	/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home

/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home
```

However, I still get the error "Unable to load Java Runtime Environment."

**Comment by ffissore** [comment]
What does `java -version` prints? Any chance we may have a video call, so you can show me your desktop and I can ask you to do some tests? Write me at f.fissore@arduino.cc is you have a free quarter of an hour

**Comment by ffissore** [comment]
Give a try to http://arduino.cc/download.php?f=/arduino-1.6.0rc3-macosx-java-latest.zip in the mean time

**Comment by ffissore** [comment]
Fixed with IDE 1.6.0 release. If you still have problems, please open a new issue
