### ISSUE TITLE
[Add library] CD74HC4067

### ISSUE THREAD

**Issue by waspinator** [arduino/Arduino#5516]
https://github.com/waspinator/CD74HC4067

**Comment by agdl** [comment]
Done thank you!

**Comment by waspinator** [comment]
@agdl I can't seem to find my library in the `Library Manager`. Maybe the way I prepared my library was incorrect? It's my first library I tried to add, and I'm not sure if I did everything right. Thanks.

**Comment by cmaglie** [comment]
The crawler log reports:

`2016/11/09 13:37:25 'sentence' and 'url' fields must be defined`

Please update your library.properties by adding the missing fields, commit and push the change, and redo the 1.0.0 tag.
Once done, if everything is ok, the library should be automatically published within an hour.

**Comment by waspinator** [comment]
@cmaglie I tried to update it as you described, but it's still not appearing in the Library Manager. Is there a place I can see what the log error reports?

**Comment by cmaglie** [comment]
I can see it on the library manager:

![lib](https://cloud.githubusercontent.com/assets/423515/20642950/dfbe8244-b41c-11e6-8295-d64479f899e1.png)

It may be a connection or file permission problem?

**Comment by waspinator** [comment]
@cmaglie I can see it now too. strange. thanks for looking into it. sorry for the trouble.
