### ISSUE TITLE
Keyboard shortcut for Increase Font Size not working and incorrect shortcut shown in the Edit menu

### ISSUE THREAD

**Issue by AlfGit** [arduino/Arduino#6806]
Edit menu shows Increase Font Size shortcut as 'Ctrl+ Unknown KeyCode: 0x2b'. The same behavior is seen on W10 and W7, with Logitech USB (HID keyboard device) and Microsoft PS/2 (standard PS/2 keyboard) keyboards.

**Comment by per1234** [comment]
![clipboard02](https://user-images.githubusercontent.com/8572152/31321865-7902c092-ac41-11e7-9cb7-b5659dc7df46.png)

**Comment by AlfGit** [comment]
Fair enough, although I think one is a consequence of the other. It appears that KeyStroke.getKeyStroke does not like '+' as an argument. To clarify, it is not only displayed incorrectly, but the shortcut Ctrl+ Plus does not work.

**Comment by per1234** [comment]
Sorry, I misunderstood the issue report because you only talked about the menu issue in the description and I tested that the new keyboard shortcut Ctrl+MouseWheel was working correctly. I forgot it is also Ctrl+Plus, though I should have noticed that Ctrl+Minus is Decrease Font Size. I've updated the title. Thanks for the issue report!

**Comment by AlfGit** [comment]
Thank you. That describes the issue perfectly.

**Comment by facchinm** [comment]
I took a look at this issue and it seems quite complicated to solve.
In fact, on keyboards with english layout the `+` key is only reachable through a modifier, so it breaks the shortcut. A solution would be to use the `+` key on the NumPad but it doesn't exist either on most laptops keyboards. If we switch to `=` which is primary on en keyboards we lose the integration for a lot of other locales...
I'll think about it and report back if I find something interesting/feasible.

**Comment by AlfGit** [comment]
The + and - on the numpad are already assigned to opening and folding code blocks, which I would say is far more useful because it's a function that would likely be used repeatedly. I imagine that most people would set their preferred font size once and then leave it, and there is still Ctrl+ mousewheel for those of us that use zoom more often. Of course, not all users have mousewheel functionality either, especially those using a trackpad on a laptop.

**Comment by Bradfo69** [comment]
Try to change your [keyboard](https://www.icrfq.com/family/314). A few months ago I got the same issues and I'm trying too may way to solve this but I can't.

**Comment by ElectricRCAircraftGuy** [comment]
This problem still exists...
Running a Dell Precision 7510 with Ubuntu 14.04

**Comment by facchinm** [comment]
@ElectricRCAircraftGuy would you mind testing the beta? It contains https://github.com/arduino/Arduino/commit/3d5c1bdba6bd08d45d70ea1d7b22fbc23610388f which should solve the issue for different keyboard layouts.

**Comment by ElectricRCAircraftGuy** [comment]
Yeah...but I've never used the Beta. Do I need to build it or are binaries available?

**Comment by ElectricRCAircraftGuy** [comment]
Nevermind, getting it now off the "beta builds" section here: https://www.arduino.cc/en/Main/Software

**Comment by ElectricRCAircraftGuy** [comment]
I tested 1.9.0-beta and the menu looks better (no longer has that weird error), but Ctrl + PLus still does not work. Ctrl + Minus is fine

**Comment by per1234** [comment]
The Ctrl+Plus keyboard shortcut (by "Plus" I mean the =/+ key) does not work for me with Arduino IDE 1.9.0-beta build 36 on Windows 10.

**Comment by ReAlUA** [comment]
The same for 64-bit Ubuntu. Ctrl+Plus displayed correctly in menu but does not work.

**Comment by Jim-2249** [comment]
With my setup, Win 10 & 1.8.5, ctrl+wheel either way just reduces the font size.

How about disabling the wheel for font size changes? I accidentally reduce the font with the wheel then have to go to preferences to fix it. If ctrl+wheel didn't change the font size, this issue would be moot for me.

**Comment by NathanielJS1541** [comment]
I have the same problem. Also for me zooming out with the mouse wheel works, but zooming in does not.
<img width="241" alt="capture" src="https://user-images.githubusercontent.com/33491104/39099868-419f5b74-4679-11e8-8550-b3b7e18fc6c9.PNG">

Also I found it interesting that no matter which way I scroll, it always zooms out.

I have also tested this on the laptop touchpad (using two fingers on the touchpad to scroll up or down), and I get the same result.

**Comment by JayConverse** [comment]
Ditto here, Windows 10 Dell, Arduino 1.8.5, Teensyduino 1.41

**Comment by PaulStoffregen** [comment]
Mouse wheel while holding CTRL is able to scroll in and out when I try with Arduino 1.8.5 on Windows 10 and Ubuntu 14.04.

Here's a quick screen recording from Windows 10.

https://youtu.be/-z6nPbKy6Es

**Comment by JayConverse** [comment]
Thanks, Paul!  I knew that wheel thing was useful for something....

**Comment by Jim-2249** [comment]
I had tried and found ctrl+wheel only decreased font size. Just tried it again and it does both. What changed?

**Comment by PaulStoffregen** [comment]
I spent a couple hours looked into this bug (the keyboard shortcut, not scroll wheel).

The fix in 1.9 to use KeyEvent.VK_PLUS does **not** work on US keyboards, and presumably all others where '+' is typed with the shift key.

Sadly, it seems all roads not from actual keyboard input lead to "KEY_TYPED" codes & events, which don't have any awareness of the keyboard layout.  Java's KeyEvent.getExtendedKeyCodeForChar() looked like the most promising option, but it turned out to be an empty promise.  It returns VK_PLUS, even when a US keyboard is used.

Digging deeper into this, I found many references to the keyboard layout being handled by the host system.  After a couple hours, the reality started to sink in that Java doesn't seem to actually have any logic/knowledge of the keyboard layout at all.  :-(

As nearly as I can tell, the *only* solution is to query the Locale info.  But even that appears to be less ideal.  It also seems to lack any solid info about the actual keyboard layout used.  Whether to use VK_PLUS or VK_EQUALS can be clear in many common cases, but there doesn't seem to be any Java way to perfectly find this info.

**Comment by pendletonrc** [comment]
May I suggest that you simply get rid of the the keyboard shortcuts for changing font size? You provide the wheel based font zoom and you can set both the font size and GUI scale factor in the preferences menu.
Old saying from way back... when in doubt, cut it out.

**Comment by Jim-2249** [comment]
With 1.9.0 beta build 71, sometimes ctrl+scroll-up increases font size and sometimes it does not. I think I try it just after starting the program. Also, ctrl+minus works and ctrl+plus does not at the moment.

**Comment by cmaglie** [comment]
It seems that most keyboards have either "+" directly available on the base layer or as SHIFT+"=", so the simplest solution is to use two keybinding for the "Increase Font Size" action:
"CTRL +" and "SHIFT CTRL =" (to allow keyboards with "+ =" on the same key).

See #7888
